"""initial durable delivery tables

Revision: 0001
Parent:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_key", sa.String(length=300), nullable=False),
        sa.Column("repository", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_index(op.f("ix_work_items_repository"), "work_items", ["repository"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("spec_digest", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("reserved_microdollars", sa.Integer(), nullable=False),
        sa.Column("spent_microdollars", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_runs_work_item_id"), "workflow_runs", ["work_item_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("previous_state", sa.String(length=40), nullable=False),
        sa.Column("next_state", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "sequence"),
    )
    op.create_index(
        op.f("ix_audit_events_workflow_id"), "audit_events", ["workflow_id"], unique=False
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor", "idempotency_key"),
    )
    op.create_index(op.f("ix_commands_workflow_id"), "commands", ["workflow_id"], unique=False)
    op.create_table(
        "inbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("integration_id", sa.String(length=100), nullable=False),
        sa.Column("delivery_id", sa.String(length=200), nullable=False),
        sa.Column("semantic_key", sa.String(length=300), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "integration_id", "delivery_id"),
        sa.UniqueConstraint("provider", "integration_id", "digest"),
        sa.UniqueConstraint("provider", "integration_id", "semantic_key"),
    )
    op.create_table(
        "usage_reservations",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("reserved_microdollars", sa.Integer(), nullable=False),
        sa.Column("reserved_input_tokens", sa.Integer(), nullable=False),
        sa.Column("reserved_output_tokens", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("actual_microdollars", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_reservations_workflow_id"),
        "usage_reservations",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=36), nullable=False),
        sa.Column("last_error", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["commands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("command_id"),
    )
    op.create_index(op.f("ix_outbox_workflow_id"), "outbox", ["workflow_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_workflow_id"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_usage_reservations_workflow_id"), table_name="usage_reservations")
    op.drop_table("usage_reservations")
    op.drop_table("inbox")
    op.drop_index(op.f("ix_commands_workflow_id"), table_name="commands")
    op.drop_table("commands")
    op.drop_index(op.f("ix_audit_events_workflow_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_workflow_runs_work_item_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_work_items_repository"), table_name="work_items")
    op.drop_table("work_items")
    # ### end Alembic commands ###
