"""immutable specifications and operation keys

Revision: 0002
Parent: 0001
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "digest"),
    )
    op.create_index(
        op.f("ix_specifications_workflow_id"), "specifications", ["workflow_id"], unique=False
    )
    with op.batch_alter_table("usage_reservations") as batch:
        batch.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=200),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_reservations") as batch:
        batch.alter_column(
            "id",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )
    op.drop_index(op.f("ix_specifications_workflow_id"), table_name="specifications")
    op.drop_table("specifications")
    # ### end Alembic commands ###
